version: "2.1"
services: 
  vrising:
    container_name: vrising-server
    image: vrising:latest
    volumes: 
      - ${VRISING_DATA_DIR:-./data/saves}:/root/.wine/drive_c/users/root/AppData/LocalLow/Stunlock Studios/VRisingServer/Saves
      - ${VRISING_SETTINGS_DIR:-./data/settings}:/root/.wine/drive_c/users/root/AppData/LocalLow/Stunlock Studios/VRisingServer/Settings/
    ports: 
      - "27015:27015/udp"
      - "27016:27016/udp"
    restart: unless-stopped
    tty: true